attack_configs:
  seed: 1234
  shuffle: true
  use_bucket: true
  batching_key: "samples"
  batch_size: 50
  buffer_size: 100000
  save_freq: 100
  num_kept_checkpoints: 1
  victim_model: "/home/user_data/zouw/Models/save_tf_zh2en_bpe/transformer.best.final"
  victim_configs: "/home/user_data/zouw/Models/transformer_nist_zh2en_bpe.yaml"
  pinyin_data: "/home/user_data/zouw/chnchar2pinyin.dat"
  init_perturb_rate: 0.4
  gamma: 0.99
  tau: 1.0
  entropy_coef: 0.05
  value_coef: 0.5
  adversarial: true
  r_s_weight: 0.5
  r_d_weight: 10

attacker_configs:
  attacker_update_steps: 120
  attacker_model_configs:
    action_space: 2
    action_roll_space: 1
    d_word_vec: 512
    d_model: 256
    dropout: 0.2

  attacker_optimizer_configs:
    optimizer: "adafactor"
    learning_rate: 0.01
    grad_clip: -1.0
    optimizer_params: ~
    schedule_method: rsqrt
    scheduler_configs:
      d_model: 256
      warmup_steps: 100

discriminator_configs:
  discriminator_update_steps: 100
  acc_bound: 0.90
  converged_bound: 0.53
  acc_valid_freq: 10
#  acc_valid_batch_size: 50
  patience: 15

  discriminator_model_configs:
    d_word_vec: 512
    d_model: 256
    dropout: 0.2
    update_embedding: true

  discriminator_optimizer_configs:
    optimizer: "adafactor"
    learning_rate: 0.05
    grad_clip: -1.0
    optimizer_params: ~
    schedule_method: rsqrt
    scheduler_configs:
      d_model: 256
      warmup_steps: 5
