attack_configs:
  seed: 1234
  victim_model: "/home/user_data/zouw/Models/save_zhen_bpe/transformer.best.final"
  victim_configs: "/home/user_data/zouw/Models/transformer_nist_zh2en_bpe.yaml"
  init_perturb_rate: 0.4
  gamma: 0.99
  tau: 1.0
  entropy_coef: 0.05
  value_coef: 0.5

attacker_configs:
  attacker_update_steps: 120
  attacker_model_configs:
    action_space: 2
    action_roll_space: 1
    d_word_vec: 512
    d_model: 128
    dropout: 0.5

  attacker_optimizer_configs:
    optimizer: "adafactor"
    learning_rate: 0.01
    grad_clip: -1.0
    optimizer_params: ~
    schedule_method: rsqrt
    scheduler_configs:
      d_model: 128
      warmup_steps: 100

discriminator_data_configs:
  valid_data:
  - "/home/user_data/weihr/NMT_DATA_PY3/NIST-ZH-EN/test/mt03.src"
  - "/home/user_data/weihr/NMT_DATA_PY3/NIST-ZH-EN/test/mt03.ref0"

discriminator_configs:
  discriminator_update_steps: 80
  acc_bound: 0.85
  acc_valid_freq: 10
  acc_valid_batch_size: 50
  patience: 5

  discriminator_model_configs:
    d_word_vec: 512
    d_model: 128
    dropout: 0.
    update_embedding: true

  discriminator_optimizer_configs:
    optimizer: "adafactor"
    learning_rate: 0.05
    grad_clip: -1.0
    optimizer_params: ~
    schedule_method: rsqrt
    scheduler_configs:
      d_model: 128
      warmup_steps: 5

training_configs:
  seed: 1234
  max_epochs: 20
  shuffle: true
  use_bucket: true
  batch_size: 256
  buffer_size: 1024
  batching_key: "samples"
  update_cycle: 4
  valid_batch_size: 50
  disp_freq: 100
  save_freq: 100
  num_kept_checkpoints: 1
  num_kept_best_model: 1
  loss_valid_freq: 10

