data_configs:
  lang_pair: "en-fr"
  train_data:
    - "/home/user_data/zouw/small_en2fr/train/train_enfr.en.tok"
    - "/home/user_data/zouw/small_en2fr/train/train_enfr.fr.tok"
  valid_data:
    - "/home/user_data/zouw/small_en2fr/dev/dev.en.tok"
    - "/home/user_data/zouw/small_en2fr/dev/dev.fr.tok"
  bleu_valid_reference: "/home/user_data/zouw/small_en2fr/dev/dev.fr.tok"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/user_data/zouw/small_en2fr/vocab/vocab.bpe30k.en"
      codes: "/home/user_data/zouw/small_en2fr/vocab/code.bpe30k.en"
      max_n_words: -1
    - type: "bpe"
      dict_path: "/home/user_data/zouw/small_en2fr/vocab/vocab.bpe30k.fr"
      max_n_words: -1
      codes: "/home/user_data/zouw/small_en2fr/vocab/code.bpe30k.fr"
  max_len:
    - 128
    - 128
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: true
  use_bucket: true
  batch_size: 2500
  batching_key: "tokens"
  update_cycle: 4
  valid_batch_size: 20
  disp_freq: 500
  save_freq: 1000
  num_kept_checkpoints: 1
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 20
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50
